### PR TITLE
Add execution modes CONFIGURE, START, RESTART.

### LINKED ISSUE #28: Fast turnarounds / live coding comparable to PDE
maven-osgi-exec-plugin requires to run at least Maven test or package phases to collect the build artifacts. Especially in multi-module projects this may lead to long delays until the OSGi framework is started.

I thought about introducing the possibility to just restart Equinox without running through a whole reactor build via a Gogo command or by using a special launcher application. This behviour would be similar to using the PDE launcher of Eclipse that also just relies on the existing build artifacts.

Are there any (other) ideas how this could be implemented for maven-osgi-exec-plugin?

### PR DESCRIPTION
**Pull request by kenwenzel**
Fixes #28 

This change allows to restart a configuration created by osgi-exec
without running through a complete Maven reactor build.
The current functionality is unaffected.

### CODE REVIEW

**Comment by kenwenzel** [comment]
I try to add some kind of test.

**Comment by kenwenzel** [comment]
Meanwhile you can see it in action here:
[komma-launch](https://github.com/komma/komma/blob/master/launch/pom.xml)

Just clone the repo and change to the launch directory.
Then run:
- `mvn test -DskipTests` for configuration and start
- `mvn test -P restart` for restart

**Comment by kenwenzel** [comment]
OK, I've added a very basic test case using Maven Verifier.
The test is more or less only for demonstration purposes and
needs some more work to be really useful.

**Comment by tomsontom** [comment]
As we don't have a CLA in place but if we maybe eg one day wrap that into efxclipse or some other eclipse project let me ask you the following questions (which I assume you answer with yes):
* Did you write all the code yourself?
* Are you allowed to contribute your code?
Beside that I'm fine with those changes so once you answered them we can merge them.

**Comment by kenwenzel** [comment]
I've just converted the mode names to lower case as other Maven plugins also do.

> As we don't have a CLA in place but if we maybe eg one day wrap that into efxclipse or some other eclipse project let me ask you the following questions (which I assume you answer with yes):
> 
> * Did you write all the code yourself?
> * Are you allowed to contribute your code?
>   Beside that I'm fine with those changes so once you answered them we can merge them.

Yes and yes :-)

**Comment by tomsontom** [comment]
looks like the conversion to lower case broke - the e4 sample - https://github.com/BestSolution-at/e4-efxclipse-maven-sample/issues/14#issuecomment-616201690

**Comment by kenwenzel** [comment]
I will fix it immediately.

**Pull request merged**
